import {defaultTheme, ZnUITheme} from "@znui/react";

const mainFont = "Roboto"

// const fonts = {
//     "dinroundpro_light.otf": {
//         style: "normal",
//         weight: "300",
//     },
//     "dinroundpro.otf": {
//         style: "normal",
//         weight: "400",
//     },
//     "dinroundpro_medi.otf": {
//         style: "normal",
//         weight: "500",
//     },
//     "dinroundpro_bold.otf": {
//         style: "normal",
//         weight: "600",
//     },
//     "dinroundpro_black.otf": {
//         style: "normal",
//         weight: "700",
//     },
// }
//
// for (const font of Object.keys(fonts)) {
//     document.fonts.add(
//         new FontFace(
//             mainFont,
//             `url(/${font}), format("opentype")`,
//             fonts[font]
//         )
//     );
// }


export const theme: ZnUITheme = Object.assign({}, defaultTheme, {
    palettes: {
        "primary": {
            "0": "#000000",
            "5": "#00102D",
            "10": "#001A41",
            "15": "#002455",
            "20": "#092F65",
            "25": "#193A70",
            "30": "#27467C",
            "35": "#345289",
            "40": "#415E96",
            "50": "#5A77B1",
            "60": "#7490CC",
            "70": "#8EABE8",
            "80": "#ADC6FF",
            "90": "#D8E2FF",
            "95": "#EDF0FF",
            "98": "#F9F9FF",
            "99": "#FEFBFF",
            "100": "#FFFFFF"
        },
        "secondary": {
            "0": "#000000",
            "5": "#0B111D",
            "10": "#161B28",
            "15": "#202632",
            "20": "#2B303E",
            "25": "#363B49",
            "30": "#414755",
            "35": "#4D5261",
            "40": "#595E6D",
            "50": "#717786",
            "60": "#8B90A0",
            "70": "#A6ABBB",
            "80": "#C1C6D7",
            "90": "#DDE2F4",
            "95": "#EDF0FF",
            "98": "#F9F9FF",
            "99": "#FEFBFF",
            "100": "#FFFFFF"
        },
        "tertiary": {
            "0": "#000000",
            "5": "#1B0A1E",
            "10": "#271529",
            "15": "#321F34",
            "20": "#3D2A3F",
            "25": "#49354A",
            "30": "#554056",
            "35": "#614B62",
            "40": "#6D576F",
            "50": "#876F88",
            "60": "#A289A2",
            "70": "#BEA3BD",
            "80": "#DABED9",
            "90": "#F7DAF6",
            "95": "#FFEBFC",
            "98": "#FFF7FA",
            "99": "#FFFBFF",
            "100": "#FFFFFF"
        },
        "neutral": {
            "0": "#000000",
            "5": "#101113",
            "10": "#1B1B1E",
            "15": "#252628",
            "20": "#303033",
            "25": "#3B3B3E",
            "30": "#464649",
            "35": "#525255",
            "40": "#5E5E61",
            "50": "#777779",
            "60": "#919093",
            "70": "#ACABAE",
            "80": "#C7C6C9",
            "90": "#E4E2E5",
            "95": "#F2F0F3",
            "98": "#FBF8FC",
            "99": "#FEFBFF",
            "100": "#FFFFFF"
        },
        "neutral-variant": {
            "0": "#000000",
            "5": "#0F1116",
            "10": "#191B21",
            "15": "#24262B",
            "20": "#2E3036",
            "25": "#393B41",
            "30": "#45474D",
            "35": "#515258",
            "40": "#5D5E65",
            "50": "#75777D",
            "60": "#8F9097",
            "70": "#AAABB2",
            "80": "#C5C6CD",
            "90": "#E2E2E9",
            "95": "#F0F0F8",
            "98": "#F9F9FF",
            "99": "#FEFBFF",
            "100": "#FFFFFF"
        }
    },
    schemes: {
        light: {
            "primary": "#445E91",
            "surfaceTint": "#445E91",
            "onPrimary": "#FFFFFF",
            "primaryContainer": "#D8E2FF",
            "onPrimaryContainer": "#2B4678",
            "secondary": "#575E71",
            "onSecondary": "#FFFFFF",
            "secondaryContainer": "#DBE2F9",
            "onSecondaryContainer": "#3F4759",
            "tertiary": "#715573",
            "onTertiary": "#FFFFFF",
            "tertiaryContainer": "#FBD7FC",
            "onTertiaryContainer": "#583E5B",
            "error": "#BA1A1A",
            "onError": "#FFFFFF",
            "errorContainer": "#FFDAD6",
            "onErrorContainer": "#93000A",
            "background": "#F9F9FF",
            "onBackground": "#1A1B20",
            "surface": "#F9F9FF",
            "onSurface": "#1A1B20",
            "surfaceVariant": "#E1E2EC",
            "onSurfaceVariant": "#44474F",
            "outline": "#75777F",
            "outlineVariant": "#C4C6D0",
            "shadow": "#000000",
            "scrim": "#000000",
            "inverseSurface": "#2F3036",
            "inverseOnSurface": "#F0F0F7",
            "inversePrimary": "#ADC6FF",
            "primaryFixed": "#D8E2FF",
            "onPrimaryFixed": "#001A41",
            "primaryFixedDim": "#ADC6FF",
            "onPrimaryFixedVariant": "#2B4678",
            "secondaryFixed": "#DBE2F9",
            "onSecondaryFixed": "#141B2C",
            "secondaryFixedDim": "#BFC6DC",
            "onSecondaryFixedVariant": "#3F4759",
            "tertiaryFixed": "#FBD7FC",
            "onTertiaryFixed": "#29132D",
            "tertiaryFixedDim": "#DEBCDF",
            "onTertiaryFixedVariant": "#583E5B",
            "surfaceDim": "#D9D9E0",
            "surfaceBright": "#F9F9FF",
            "surfaceContainerLowest": "#FFFFFF",
            "surfaceContainerLow": "#F3F3FA",
            "surfaceContainer": "#EEEDF4",
            "surfaceContainerHigh": "#E8E7EE",
            "surfaceContainerHighest": "#E2E2E9"
        },
        lightMediumContrast: {
            "primary": "#183566",
            "surfaceTint": "#445E91",
            "onPrimary": "#FFFFFF",
            "primaryContainer": "#536DA1",
            "onPrimaryContainer": "#FFFFFF",
            "secondary": "#2E3647",
            "onSecondary": "#FFFFFF",
            "secondaryContainer": "#656D80",
            "onSecondaryContainer": "#FFFFFF",
            "tertiary": "#462D49",
            "onTertiary": "#FFFFFF",
            "tertiaryContainer": "#806383",
            "onTertiaryContainer": "#FFFFFF",
            "error": "#740006",
            "onError": "#FFFFFF",
            "errorContainer": "#CF2C27",
            "onErrorContainer": "#FFFFFF",
            "background": "#F9F9FF",
            "onBackground": "#1A1B20",
            "surface": "#F9F9FF",
            "onSurface": "#0F1116",
            "surfaceVariant": "#E1E2EC",
            "onSurfaceVariant": "#33363E",
            "outline": "#50525A",
            "outlineVariant": "#6A6D75",
            "shadow": "#000000",
            "scrim": "#000000",
            "inverseSurface": "#2F3036",
            "inverseOnSurface": "#F0F0F7",
            "inversePrimary": "#ADC6FF",
            "primaryFixed": "#536DA1",
            "onPrimaryFixed": "#FFFFFF",
            "primaryFixedDim": "#3A5487",
            "onPrimaryFixedVariant": "#FFFFFF",
            "secondaryFixed": "#656D80",
            "onSecondaryFixed": "#FFFFFF",
            "secondaryFixedDim": "#4D5567",
            "onSecondaryFixedVariant": "#FFFFFF",
            "tertiaryFixed": "#806383",
            "onTertiaryFixed": "#FFFFFF",
            "tertiaryFixedDim": "#674C69",
            "onTertiaryFixedVariant": "#FFFFFF",
            "surfaceDim": "#C6C6CD",
            "surfaceBright": "#F9F9FF",
            "surfaceContainerLowest": "#FFFFFF",
            "surfaceContainerLow": "#F3F3FA",
            "surfaceContainer": "#E8E7EE",
            "surfaceContainerHigh": "#DCDCE3",
            "surfaceContainerHighest": "#D1D1D8"
        },
        lightHighContrast: {
            "primary": "#0A2B5B",
            "surfaceTint": "#445E91",
            "onPrimary": "#FFFFFF",
            "primaryContainer": "#2E487A",
            "onPrimaryContainer": "#FFFFFF",
            "secondary": "#242C3D",
            "onSecondary": "#FFFFFF",
            "secondaryContainer": "#41495B",
            "onSecondaryContainer": "#FFFFFF",
            "tertiary": "#3B233F",
            "onTertiary": "#FFFFFF",
            "tertiaryContainer": "#5A405D",
            "onTertiaryContainer": "#FFFFFF",
            "error": "#600004",
            "onError": "#FFFFFF",
            "errorContainer": "#98000A",
            "onErrorContainer": "#FFFFFF",
            "background": "#F9F9FF",
            "onBackground": "#1A1B20",
            "surface": "#F9F9FF",
            "onSurface": "#000000",
            "surfaceVariant": "#E1E2EC",
            "onSurfaceVariant": "#000000",
            "outline": "#292C33",
            "outlineVariant": "#464951",
            "shadow": "#000000",
            "scrim": "#000000",
            "inverseSurface": "#2F3036",
            "inverseOnSurface": "#FFFFFF",
            "inversePrimary": "#ADC6FF",
            "primaryFixed": "#2E487A",
            "onPrimaryFixed": "#FFFFFF",
            "primaryFixedDim": "#143162",
            "onPrimaryFixedVariant": "#FFFFFF",
            "secondaryFixed": "#41495B",
            "onSecondaryFixed": "#FFFFFF",
            "secondaryFixedDim": "#2B3344",
            "onSecondaryFixedVariant": "#FFFFFF",
            "tertiaryFixed": "#5A405D",
            "onTertiaryFixed": "#FFFFFF",
            "tertiaryFixedDim": "#422A46",
            "onTertiaryFixedVariant": "#FFFFFF",
            "surfaceDim": "#B8B8BF",
            "surfaceBright": "#F9F9FF",
            "surfaceContainerLowest": "#FFFFFF",
            "surfaceContainerLow": "#F0F0F7",
            "surfaceContainer": "#E2E2E9",
            "surfaceContainerHigh": "#D4D4DB",
            "surfaceContainerHighest": "#C6C6CD"
        },
        dark: {
            "primary": "#ADC6FF",
            "surfaceTint": "#ADC6FF",
            "onPrimary": "#102F60",
            "primaryContainer": "#2B4678",
            "onPrimaryContainer": "#D8E2FF",
            "secondary": "#BFC6DC",
            "onSecondary": "#293041",
            "secondaryContainer": "#3F4759",
            "onSecondaryContainer": "#DBE2F9",
            "tertiary": "#DEBCDF",
            "onTertiary": "#402843",
            "tertiaryContainer": "#583E5B",
            "onTertiaryContainer": "#FBD7FC",
            "error": "#FFB4AB",
            "onError": "#690005",
            "errorContainer": "#93000A",
            "onErrorContainer": "#FFDAD6",
            "background": "#111318",
            "onBackground": "#E2E2E9",
            "surface": "#111318",
            "onSurface": "#E2E2E9",
            "surfaceVariant": "#44474F",
            "onSurfaceVariant": "#C4C6D0",
            "outline": "#8E9099",
            "outlineVariant": "#44474F",
            "shadow": "#000000",
            "scrim": "#000000",
            "inverseSurface": "#E2E2E9",
            "inverseOnSurface": "#2F3036",
            "inversePrimary": "#445E91",
            "primaryFixed": "#D8E2FF",
            "onPrimaryFixed": "#001A41",
            "primaryFixedDim": "#ADC6FF",
            "onPrimaryFixedVariant": "#2B4678",
            "secondaryFixed": "#DBE2F9",
            "onSecondaryFixed": "#141B2C",
            "secondaryFixedDim": "#BFC6DC",
            "onSecondaryFixedVariant": "#3F4759",
            "tertiaryFixed": "#FBD7FC",
            "onTertiaryFixed": "#29132D",
            "tertiaryFixedDim": "#DEBCDF",
            "onTertiaryFixedVariant": "#583E5B",
            "surfaceDim": "#111318",
            "surfaceBright": "#37393E",
            "surfaceContainerLowest": "#0C0E13",
            "surfaceContainerLow": "#1A1B20",
            "surfaceContainer": "#1E1F25",
            "surfaceContainerHigh": "#282A2F",
            "surfaceContainerHighest": "#33353A"
        },
        darkMediumContrast: {
            "primary": "#CFDCFF",
            "surfaceTint": "#ADC6FF",
            "onPrimary": "#002454",
            "primaryContainer": "#7790C7",
            "onPrimaryContainer": "#000000",
            "secondary": "#D5DCF3",
            "onSecondary": "#1E2636",
            "secondaryContainer": "#8990A5",
            "onSecondaryContainer": "#000000",
            "tertiary": "#F5D1F5",
            "onTertiary": "#341D38",
            "tertiaryContainer": "#A687A7",
            "onTertiaryContainer": "#000000",
            "error": "#FFD2CC",
            "onError": "#540003",
            "errorContainer": "#FF5449",
            "onErrorContainer": "#000000",
            "background": "#111318",
            "onBackground": "#E2E2E9",
            "surface": "#111318",
            "onSurface": "#FFFFFF",
            "surfaceVariant": "#44474F",
            "onSurfaceVariant": "#DADCE6",
            "outline": "#B0B1BB",
            "outlineVariant": "#8E9099",
            "shadow": "#000000",
            "scrim": "#000000",
            "inverseSurface": "#E2E2E9",
            "inverseOnSurface": "#282A2F",
            "inversePrimary": "#2C4779",
            "primaryFixed": "#D8E2FF",
            "onPrimaryFixed": "#00102D",
            "primaryFixedDim": "#ADC6FF",
            "onPrimaryFixedVariant": "#183566",
            "secondaryFixed": "#DBE2F9",
            "onSecondaryFixed": "#091121",
            "secondaryFixedDim": "#BFC6DC",
            "onSecondaryFixedVariant": "#2E3647",
            "tertiaryFixed": "#FBD7FC",
            "onTertiaryFixed": "#1E0822",
            "tertiaryFixedDim": "#DEBCDF",
            "onTertiaryFixedVariant": "#462D49",
            "surfaceDim": "#111318",
            "surfaceBright": "#43444A",
            "surfaceContainerLowest": "#06070C",
            "surfaceContainerLow": "#1C1D22",
            "surfaceContainer": "#26282D",
            "surfaceContainerHigh": "#313238",
            "surfaceContainerHighest": "#3C3D43"
        },
        darkHighContrast: {
            "primary": "#ECEFFF",
            "surfaceTint": "#ADC6FF",
            "onPrimary": "#000000",
            "primaryContainer": "#A9C2FC",
            "onPrimaryContainer": "#000A22",
            "secondary": "#ECEFFF",
            "onSecondary": "#000000",
            "secondaryContainer": "#BBC2D8",
            "onSecondaryContainer": "#040B1B",
            "tertiary": "#FFEAFC",
            "onTertiary": "#000000",
            "tertiaryContainer": "#DAB8DB",
            "onTertiaryContainer": "#17031C",
            "error": "#FFECE9",
            "onError": "#000000",
            "errorContainer": "#FFAEA4",
            "onErrorContainer": "#220001",
            "background": "#111318",
            "onBackground": "#E2E2E9",
            "surface": "#111318",
            "onSurface": "#FFFFFF",
            "surfaceVariant": "#44474F",
            "onSurfaceVariant": "#FFFFFF",
            "outline": "#EEEFF9",
            "outlineVariant": "#C1C2CC",
            "shadow": "#000000",
            "scrim": "#000000",
            "inverseSurface": "#E2E2E9",
            "inverseOnSurface": "#000000",
            "inversePrimary": "#2C4779",
            "primaryFixed": "#D8E2FF",
            "onPrimaryFixed": "#000000",
            "primaryFixedDim": "#ADC6FF",
            "onPrimaryFixedVariant": "#00102D",
            "secondaryFixed": "#DBE2F9",
            "onSecondaryFixed": "#000000",
            "secondaryFixedDim": "#BFC6DC",
            "onSecondaryFixedVariant": "#091121",
            "tertiaryFixed": "#FBD7FC",
            "onTertiaryFixed": "#000000",
            "tertiaryFixedDim": "#DEBCDF",
            "onTertiaryFixedVariant": "#1E0822",
            "surfaceDim": "#111318",
            "surfaceBright": "#4E5056",
            "surfaceContainerLowest": "#000000",
            "surfaceContainerLow": "#1E1F25",
            "surfaceContainer": "#2F3036",
            "surfaceContainerHigh": "#3A3B41",
            "surfaceContainerHighest": "#45474C"
        }
    },
    typeScale: {
        display: {
            large: {
                ...defaultTheme.typeScale.display.large,
                fontFamilyName: mainFont,
            },
            medium: {
                ...defaultTheme.typeScale.display.medium,
                fontFamilyName: mainFont,
            },
            small: {
                ...defaultTheme.typeScale.display.small,
                fontFamilyName: mainFont,
            },
        },
        headline: {
            large: {
                ...defaultTheme.typeScale.headline.large,
                fontFamilyName: mainFont,
            },
            medium: {
                ...defaultTheme.typeScale.headline.medium,
                fontFamilyName: mainFont,
            },
            small: {
                ...defaultTheme.typeScale.headline.small,
                fontFamilyName: mainFont,
            },
        },
        body: {
            large: {
                ...defaultTheme.typeScale.body.large,
                fontFamilyName: mainFont,
            },
            medium: {
                ...defaultTheme.typeScale.body.medium,
                fontFamilyName: mainFont,
            },
            small: {
                ...defaultTheme.typeScale.body.small,
                fontFamilyName: mainFont,
            },
        },
        label: {
            large: {
                ...defaultTheme.typeScale.label.large,
                fontFamilyName: mainFont,
            },
            medium: {
                ...defaultTheme.typeScale.label.medium,
                fontFamilyName: mainFont,
            },
            small: {
                ...defaultTheme.typeScale.label.small,
                fontFamilyName: mainFont,
            },
        },
        title: {
            large: {
                ...defaultTheme.typeScale.title.large,
                fontFamilyName: mainFont,
            },
            medium: {
                ...defaultTheme.typeScale.title.medium,
                fontFamilyName: mainFont,
            },
            small: {
                ...defaultTheme.typeScale.title.small,
                fontFamilyName: mainFont,
            },
        },
    }
})